spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# local 환경
---
spring:
  profiles: local
  datasource:
    platform: h2
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    data: classpath:data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082
