spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# local 환경
---
spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/booklog?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
    data: classpath:data-mariadb.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  session:
    timeout: 600
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

spring.profiles.include: oauth